### ISSUE TITLE
Integrar documentación y comentarios

### ISSUE THREAD

**Issue by Chicook** [jersonmartinez/docker-compose-influxdb-telegraf-grafana#7]
Gracias, @Chicook. Integraré tales cambios en el [dashboard-complete.json](https://github.com/jersonmartinez/docker-compose-influxdb-telegraf-grafana/blob/main/grafana/dashboard-complete.json).

¿Has podido correr sin problemas el proyecto? 
Es que aún no he diseñado la documentación principal. He estado trabajando en [docs](https://github.com/jersonmartinez/docker-compose-influxdb-telegraf-grafana/tree/main/docs) por el momento.

La idea final será poder desplegar esto en un Cloud Provider como AWS / Azure / GCP.

_Originally posted by @jersonmartinez in https://github.com/jersonmartinez/docker-compose-influxdb-telegraf-grafana/issues/6#issuecomment-2296685393_

Haun no., estoy con otras cosas ando asta arriba de trabajo estos días., pero cualquier cosa aquí estoy.

**Comment by jersonmartinez** [comment]
Listo, las mejoras han sido integradas.

![image](https://github.com/user-attachments/assets/408aeca6-753b-4073-b77e-5b7a8b36f4cc)
