### ISSUE TITLE
¿Con este sistema., una Blockchain Hiria más rápido?

### ISSUE THREAD

**Issue by Chicook** [jersonmartinez/docker-compose-influxdb-telegraf-grafana#9]
Recién estoy aprendiendo a., trabajar con Python en módulos., y quisiera saber., si con este sistema la blokchain principal de la plataforma crypto que estoy desarrollando, de códigos abierto., Hiria más rápido., en lo referente., a la gestión con los usuarios.

Espero me podáis explicar un poquito sobre este tema.

**Comment by jersonmartinez** [comment]
Hola, @Chicook . Sobre este tema de blockchain, no tengo conocimiento. Siento no poder ayudarte.
